# Generated by Django 5.0.3 on 2024-04-15 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Communityy', '0001_initial'),
        ('User', '0002_rename_nickname_user_nickname_and_more'),
        ('UserCommunityy', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserRole',
            new_name='UserCommunityy',
        ),
    ]
