# Generated by Django 5.0.4 on 2024-04-27 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitytemplate',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
