# Generated by Django 5.0.4 on 2024-05-03 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0002_communitytemplate_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.JSONField(default=dict),
        ),
    ]
