version: '3.8'

services:
  db:
    image: postgres:16.2
    environment:
      POSTGRES_DB: django_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./db_data:/var/lib/postgresql/data

  web:
    build: .
    command: gunicorn Commune.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env  # Ensure this points to your .env file

volumes:
  postgres_data:
