# Generated by Django 5.0.3 on 2024-04-13 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserRole', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrole',
            old_name='created_at',
            new_name='createdDate',
        ),
    ]
