# Generated by Django 5.0.3 on 2024-04-13 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Role', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='rolename',
            new_name='roleName',
        ),
    ]
